class Epg(object):
    def __init__(self):
        self.epg = dict()
        self.epg['FR - TF1 FHD'] = {'channel_id': 'TF1.fr'}
        self.epg['FR - FRANCE 2 FHD'] = {'channel_id': 'France2.fr'}
        self.epg['FR - FRANCE 3 FHD'] = {'channel_id': 'France3.fr'}
        self.epg['FR - FRANCE 4 FHD'] = {'channel_id': 'France4.fr'}
        self.epg['FR - FRANCE 5 FHD'] = {'channel_id': 'France5'}
        self.epg['FR - FRANCE O FHD'] = {'channel_id': 'FranceO.fr'}
        self.epg['FR - M6 FHD'] = {'channel_id': 'M6.fr'}
        self.epg['FR - TMC FHD'] = {'channel_id': 'TMC.fr'}
        self.epg['FR - TV BREIZH FHD'] = {'channel_id': 'TVBreizh'}
        self.epg['FR - 6TER FHD'] = {'channel_id': '6ter.fr'}
        self.epg['FR - ARTE FHD'] = {'channel_id': 'Arte.fr'}
        self.epg['FR - CANAL  FHD'] = {'channel_id': 'CANALplus.fr'}
        self.epg['FR - CANAL  DECALE FHD'] = {'channel_id': 'CANALplusDECALE.fr'}
        self.epg['FR - CANAL  FAMILY FHD'] = {'channel_id': 'CANALplusFamily.fr'}
        self.epg['FR - CANAL  CINEMA FHD'] = {'channel_id': 'CANALplusCINEMA.fr'}
        self.epg['FR - OCS MAX FHD'] = {'channel_id': 'OCSMax'}
        self.epg['FR - OCS GEANTS FHD'] = {'channel_id': 'OCSGeants'}
        self.epg['FR - OCS CITY FHD'] = {'channel_id': 'OCSCity'}
        self.epg['FR - OCS CHOC FHD'] = {'channel_id': 'OCSChoc'}
        self.epg['FR - CINE  PREMIER FHD'] = {'channel_id': 'CinecinemaPremier.fr'}
        self.epg['FR - CINE  FRISSON FHD'] = {'channel_id': 'CinecinemaFrisson.fr'}
        self.epg['FR - CINE  FAMIZ FHD'] = {'channel_id': 'CinecinemaFamiz.fr'}
        self.epg['FR - CINE  EMOTION FHD'] = {'channel_id': 'CinecinemaEmotion.fr'}
        self.epg['FR - ACTION FHD'] = {'channel_id': 'Action'}
        self.epg['FR - CINE  CLUB FHD'] = {'channel_id': 'CinecinemaClub.fr'}
        self.epg['FR - CINE POLAR FHD'] = {'channel_id': 'PolarPlus'}
        self.epg['FR - CINE  CLASSIC FHD'] = {'channel_id': 'CinecinemaClassic.fr'}
        self.epg['FR - CINE FX FHD'] = {'channel_id': 'Ciné FX'}
        self.epg['FR - PARAMOUNT CHANNEL FHD'] = {'channel_id': 'ParamountChannel.fr'}
        self.epg['FR - CANAL  SPORT FHD'] = {'channel_id': 'CANALplusSPORT.fr'}
        self.epg['FR - BEINSPORT1 FHD'] = {'channel_id': 'beINSPORTS1'}
        self.epg['FR - BEINSPORT2 FHD'] = {'channel_id': 'beINSPORTS2'}
        self.epg['FR - BEINSPORT3 FHD'] = {'channel_id': 'beINSPORTS3'}
        self.epg['FR - BFM TV FHD'] = {'channel_id': 'BFMTV.fr'}
        self.epg['FR - INFOSPORT FHD'] = {'channel_id': 'Infosportplus'}
        self.epg['FR - L\'EQUIPE21 FHD'] = {'channel_id': 'EquipeTV.fr'}
        self.epg['FR - MOTORSPORT TV FHD'] = {'channel_id': 'Motors TV'}
        self.epg['FR - EUROSPORT1 FHD'] = {'channel_id': 'EurosportFrance'}
        self.epg['FR - EUROSPORT2 FHD'] = {'channel_id': 'Eurosport2France'}
        self.epg['FR - EXTREME SPORTS FHD'] = {'channel_id': 'ExtremeSports1'}
        self.epg['FR - EQUIDIA LIVE FHD'] = {'channel_id': 'EquidiaLive.fr'}
        self.epg['FR - EQUIDIA LIFE FHD'] = {'channel_id': 'Equidia Life'}
        self.epg['FR - SFR SPORT1 FHD'] = {'channel_id': 'SFRSport1.fr'}
        self.epg['FR - SFR SPORT2 FHD'] = {'channel_id': 'SFRSport2.fr'}
        self.epg['FR - SFR SPORT3 FHD'] = {'channel_id': 'SFRSport3.fr'}
        self.epg['FR - SFR SPORT5 FHD'] = {'channel_id': 'SFRSport5.fr'}
        self.epg['FR - GOLF  FHD'] = {'channel_id': 'Golfplus'}
        self.epg['FR - GOLF CHANNEL FHD'] = {'channel_id': 'GolfChannel'}
        self.epg['FR - CANAL  SERIES FHD'] = {'channel_id': 'CanalplusSeries.fr'}
        self.epg['FR - 13EME RUE FHD'] = {'channel_id': '13eRue'}
        self.epg['FR - COMEDIE  FHD'] = {'channel_id': 'Comedie.fr'}
        self.epg['FR - E! ENTERTAINMENT FHD'] = {'channel_id': 'E!F'}
        self.epg['FR - BET FHD'] = {'channel_id': 'BET'}
        self.epg['FR - CHERIE 25 FHD'] = {'channel_id': 'Cherie25.fr'}
        self.epg['FR - CSTAR FHD'] = {'channel_id': 'CStar.fr'}
        self.epg['FR - RTL9 FHD'] = {'channel_id': 'RTL9.fr'}
        self.epg['FR - NUMERO 23 FHD'] = {'channel_id': 'Numero23.fr'}
        self.epg['FR - W9 FHD'] = {'channel_id': 'W9.fr'}
        self.epg['FR - AB3 FHD'] = {'channel_id': 'AB3'}
        self.epg['FR - CANAL8 FHD'] = {'channel_id': 'C8.fr'}
        self.epg['FR - RTS DEUX FHD'] = {'channel_id': 'RTSDeux'}
        self.epg['FR - RTS UN FHD'] = {'channel_id': 'RTSUn'}
        self.epg['FR - ONE TV FHD'] = {'channel_id': 'One TV'}
        self.epg['FR - TCM CINEMA FHD'] = {'channel_id': 'TCMcinema'}
        self.epg['FR - CRIME DISTRICT FHD'] = {'channel_id': 'CrimeDistrict'}
        self.epg['FR - SYFY FHD'] = {'channel_id': 'SyFyF'}
        self.epg['FR -ELLE GIRL FHD'] = {'channel_id': 'ElleGirl'}
        self.epg['FR - AB1 FHD'] = {'channel_id': 'AB1.fr'}
        self.epg['FR - NT1 FHD'] = {'channel_id': 'NT1.fr'}
        self.epg['FR - RFM TV FHD'] = {'channel_id': 'RFMTV'}
        self.epg['FR - DISNEY CHANNEL FHD'] = {'channel_id': 'DisneyChannel'}
        self.epg['FR - DISNEY XD FHD'] = {'channel_id': 'DisneyXD'}
        self.epg['FR - NICKELODEON FHD'] = {'channel_id': 'NickelodeonFr'}
        self.epg['FR - PIWI FHD'] = {'channel_id': 'PIWI.fr'}
        self.epg['FR - BOOMERANG FHD'] = {'channel_id': 'BoomerangF'}
        self.epg['FR - DISNEY JUNIOR FHD'] = {'channel_id': 'DisneyJunior'}
        self.epg['FR - CARTOON NETWORK FHD'] = {'channel_id': 'CartoonNetwork'}
        self.epg['FR - CANAL J FHD'] = {'channel_id': 'CanalJ'}
        self.epg['FR - TIJI FHD'] = {'channel_id': 'Tiji'}
        self.epg['FR - BOING FHD'] = {'channel_id': 'Boing'}
        self.epg['FR - TELETOON  FHD'] = {'channel_id': 'TeleTOON.fr'}
        self.epg['FR - GAME ONE FHD'] = {'channel_id': 'GameOne.fr'}
        self.epg['FR - GULLI FHD'] = {'channel_id': 'Gulli.fr'}
        self.epg['FR - MANGA FHD'] = {'channel_id': 'Mangas'}
        self.epg['FR - DISNEY CINEMA FHD'] = {'channel_id': 'DisnCineHD'}
        self.epg['FR - PLANETE  FHD'] = {'channel_id': 'PLANETE.fr'}
        self.epg['FR - PLANETE AE FHD'] = {'channel_id': 'PLANETEnoLIMIT.fr'}
        self.epg['FR - PLANETE CI FHD'] = {'channel_id': 'PLANETEJustice.fr'}
        self.epg['FR - DISCOVERY FHD'] = {'channel_id': 'DiscoveryChannelFrance'}
        self.epg['FR - DISCOVERY SCIENCE FHD'] = {'channel_id': 'DiscoveryScience'}
        self.epg['FR - NGC FHD'] = {'channel_id': 'NationalGeographicChannelFrance'}
        self.epg['FR - NGC WILD FHD'] = {'channel_id': 'NatGeoWildFrance'}
        self.epg['FR - ANIMAUX FHD'] = {'channel_id': 'Animaux'}
        self.epg['FR - USHUAIA TV FHD'] = {'channel_id': 'Ushuaia'}
        self.epg['FR - RMC DECOUVERTE FHD'] = {'channel_id': 'RMCdecouverte.fr'}
        self.epg['FR - VOYAGE FHD'] = {'channel_id': 'Voyage'}
        self.epg['FR - TREK FHD'] = {'channel_id': 'TREK'}
        self.epg['FR - HISTOIRE FHD'] = {'channel_id': 'Histoire'}
        self.epg['FR - SCIENCES & VIE FHD'] = {'channel_id': 'ScienceetVieTV'}
        self.epg['FR - SEASON FHD'] = {'channel_id': 'Seasons.fr'}
        self.epg['FR - CANAL NEWS FHD'] = {'channel_id': 'CNews.fr'}
        self.epg['FR - BFM BUSINESS FHD'] = {'channel_id': 'BFMBusiness.fr'}
        self.epg['FR - LCI FHD'] = {'channel_id': 'LCI'}
        self.epg['FR - FRANCE INFO FHD'] = {'channel_id': 'franceinfo'}
        self.epg['FR - I24 NEWS FHD'] = {'channel_id': 'i24News'}
        self.epg['FR - TRACE URBAN FHD'] = {'channel_id': 'TraceUrban'}
        self.epg['FR - MTV FRANCE FHD'] = {'channel_id': 'MTVF'}
        self.epg['FR - MTV HITS FHD'] = {'channel_id': 'MTVHits'}
        self.epg['FR - MCM TOP FHD'] = {'channel_id': 'MCMTop'}
        self.epg['FR - MCM FHD'] = {'channel_id': 'MCM.fr'}
        self.epg['FR - MEZZO FHD'] = {'channel_id': 'Mezzo'}
        self.epg['FR - MEZZO LIVE FHD'] = {'channel_id': 'MezzoLive'}

        self.epg['FR - PARIS PREMIERE HD'] = {'channel_id': 'ParisPremiere.fr'}
        self.epg['FR - CANAL SAVOIR HD'] = {'channel_id': 'CanalSavoir'}
        self.epg['FR - RMC SPORT NEWS'] = {'channel_id': 'RMC Sport News'}
        self.epg['FR - RMC SPORT 1 HD'] = {'channel_id': 'SFRSport1.fr'}
        self.epg['FR - RMC SPORT 2 HD'] = {'channel_id': 'SFRSport2.fr'}
        self.epg['FR - RMC SPORT 3 HD'] = {'channel_id': 'SFRSport3.fr'}
        self.epg['FR - RMC SPORT 4 HD'] = {'channel_id': 'SFRSport5.fr'}
        self.epg['FR - RMC ACCESS SPORT 1 HD'] = {'channel_id': 'RMCSportAccess1'}
        self.epg['FR - RMC ACCESS SPORT 2 HD'] = {'channel_id': 'RMCSportAccess2'}
        self.epg['FR - RMC ACCESS SPORT 3 HD'] = {'channel_id': 'RMCSportAccess3'}
        self.epg['FR - RMC ACCESS SPORT 4 HD'] = {'channel_id': 'RMC Sport Access 4'}
        self.epg['FR - BEIN SPORT MAX 4 HD'] = {'channel_id': 'beINSPORTS4'}
        self.epg['FR - BEIN SPORT MAX 5 HD .'] = {'channel_id': 'beINSPORTS5'}
        self.epg['FR - BEIN SPORT MAX 6 HD'] = {'channel_id': 'beINSPORTS6'}
        self.epg['FR - BEIN SPORT MAX 7 HD'] = {'channel_id': 'beINSPORTS7'}
        self.epg['FR - BEIN SPORT MAX 8 HD'] = {'channel_id': 'beINSPORTS8'}
        self.epg['FR - BEIN SPORT MAX 9 HD'] = {'channel_id': 'beINSPORTS9'}
        self.epg['FR - BFM SPORT HD'] = {'channel_id': 'BFMSport'}
        self.epg['FR - FOOT 24 HD'] = {'channel_id': 'Footplus2424'}
        self.epg['FR - AB MOTEUR HD'] = {'channel_id': 'ABMoteurs'}
        self.epg['FR - TEVA HD'] = {'channel_id': 'Teva.fr'}
        self.epg['FR - NRJ 12 HD'] = {'channel_id': 'NRJ12.fr'}
        self.epg['FR - TV 5 MONDE HD'] = {'channel_id': 'TV5MONDE'}
        self.epg['FR - HD1 HD'] = {'channel_id': 'HD1.fr'}
        self.epg['FR - KTO HD'] = {'channel_id': 'KTO'}
        self.epg['FR - SERIE CLUB HD'] = {'channel_id': 'SerieClub.fr'}
        self.epg['FR - TOONAMI HD'] = {'channel_id': 'Toonami'}
        self.epg['FR - TFX HD'] = {'channel_id': 'NT1.fr'}
        self.epg['FR - DISCOVERY INVESTIGATION HD'] = {'channel_id': 'DiscoveryInvestigationF'}
        self.epg['|FR| VICELAND HD'] = {'channel_id': 'Viceland'}
        self.epg['FR - EURONEWS HD'] = {'channel_id': 'EuronewsF'}
        self.epg['FR - LCP HD'] = {'channel_id': 'LCP.fr'}
        self.epg['FR - M6 MUSIC'] = {'channel_id': 'M6Music'}
        self.epg['FR - VH1 CLASSIC'] = {'channel_id': 'VH1Classic'}

    def find(self, channel):
        return self.epg[channel]

    def channels(self):
        return self.epg.keys()
