# based on http://epg.koditvepg2.com/FR/guide.xml
class Epg(object):
    def __init__(self):
        self.epg = dict()
        self.epg['FR - TF1 FHD'] = {'channel_id': 'TF1'}
        self.epg['FR - FRANCE 2 FHD'] = {'channel_id': 'France 2'}
        self.epg['FR - FRANCE 3 FHD'] = {'channel_id': 'France 3'}
        self.epg['FR - FRANCE 4 FHD'] = {'channel_id': 'France 4'}
        self.epg['FR - FRANCE 5 FHD'] = {'channel_id': 'France 5'}
        self.epg['FR - FRANCE O FHD'] = {'channel_id': 'France Ô'}
        self.epg['FR - M6 FHD'] = {'channel_id': 'M6'}
        self.epg['FR - ARTE FHD'] = {'channel_id': 'Arte'}
        self.epg['FR - RTS DEUX FHD'] = {'channel_id': 'RTS Deux'}
        self.epg['FR - RTS UN FHD'] = {'channel_id': 'RTS Un'}
        self.epg['FR - CANAL  FHD'] = {'channel_id': 'Canal+'}
        self.epg['FR - CANAL  CINEMA FHD'] = {'channel_id': 'Canal+ cinéma'}
        self.epg['FR - CANAL  DECALE FHD'] = {'channel_id': 'Canal+ Décalé'}
        self.epg['FR - CANAL  FAMILY FHD'] = {'channel_id': 'Canal+ Family'}
        self.epg['FR - CANAL  SERIES FHD'] = {'channel_id': 'Canal+ Séries'}
        self.epg['FR - CANAL  SPORT FHD'] = {'channel_id': 'Canal+ sport'}
        self.epg['FR - CINE  CLUB FHD'] = {'channel_id': 'Ciné+ Club'}
        self.epg['FR - CINE  EMOTION FHD'] = {'channel_id': 'Ciné+ Emotion'}
        self.epg['FR - CINE  PREMIER FHD'] = {'channel_id': 'Ciné+ Premier'}
        self.epg['FR - CINE  FRISSON FHD'] = {'channel_id': 'Ciné+ Frisson'}
        self.epg['FR - CINE  CLASSIC FHD'] = {'channel_id': 'Ciné+ Classic'}
        self.epg['FR - CINE  FAMIZ FHD'] = {'channel_id': 'Ciné+ Famiz'}
        self.epg['FR - OCS CHOC FHD'] = {'channel_id': 'OCS Choc'}
        self.epg['FR - OCS CITY FHD'] = {'channel_id': 'OCS City'}
        self.epg['FR - OCS GEANTS FHD'] = {'channel_id': 'OCS Géants'}
        self.epg['FR - OCS MAX FHD'] = {'channel_id': 'OCS Max'}
        self.epg['FR - DISNEY CINEMA FHD'] = {'channel_id': 'Disney Cinema'}
        self.epg['FR - TCM CINEMA FHD'] = {'channel_id': 'TCM Cinéma'}
        self.epg['FR - ACTION FHD'] = {'channel_id': 'Action'}
        self.epg['FR - CINE FX FHD'] = {'channel_id': 'Ciné FX'}
        self.epg['FR - CINE POLAR FHD'] = {'channel_id': 'Ciné Polar'}
        self.epg['FR - CRIME DISTRICT FHD'] = {'channel_id': 'Crime District'}
        self.epg['FR - COMEDIE  FHD'] = {'channel_id': 'Comédie+'}
        self.epg['FR - 13EME RUE FHD'] = {'channel_id': '13e Rue'}
        self.epg['FR - SYFY FHD'] = {'channel_id': 'Sy Fy'}
        self.epg['FR - MTV HITS FHD'] = {'channel_id': 'MTV Hits'}
        self.epg['FR - ELLE GIRL FHD'] = {'channel_id': 'Elle Girl'}
        self.epg['FR - E! ENTERTAINMENT FHD'] = {'channel_id': 'E ! Entertainment'}
        self.epg['FR - GAME ONE FHD'] = {'channel_id': 'Game One'}
        self.epg['FR - MANGA FHD'] = {'channel_id': 'Mangas'}
        self.epg['FR - AB1 FHD'] = {'channel_id': 'AB 1'}
        self.epg['FR - TV BREIZH FHD'] = {'channel_id': 'TV Breizh'}
        self.epg['FR - RTL9 FHD'] = {'channel_id': 'RTL9'}
        self.epg['FR - BET FHD'] = {'channel_id': 'BET'}
        self.epg['FR - W9 FHD'] = {'channel_id': 'W9'}
        self.epg['FR - TMC FHD'] = {'channel_id': 'TMC'}
        self.epg['FR - NT1 FHD'] = {'channel_id': 'NT1'}
        self.epg['FR - CSTAR FHD'] = {'channel_id': 'CStar'}
        self.epg['FR - 6TER FHD'] = {'channel_id': '6Ter'}
        self.epg['FR - NUMERO 23 FHD'] = {'channel_id': 'Numéro 23'}
        self.epg['FR - CHERIE 25 FHD'] = {'channel_id': 'Chérie 25'}
        self.epg['FR - PLANETE  FHD'] = {'channel_id': 'Planète+'}
        self.epg['FR - PLANETE AE FHD'] = {'channel_id': 'Planète+ A&E'}
        self.epg['FR - PLANETE CI FHD'] = {'channel_id': 'Planète+ CI'}
        self.epg['FR - NGC FHD'] = {'channel_id': 'National Geographic'}
        self.epg['FR - NGC WILD FHD'] = {'channel_id': 'Nat Geo Wild'}
        self.epg['FR - DISCOVERY FHD'] = {'channel_id': 'Discovery Channel'}
        self.epg['FR - DISCOVERY SCIENCE FHD'] = {'channel_id': 'Discovery Science'}
        self.epg['FR - DISCOVERY INVESTIGATION HD'] = {'channel_id': 'Discovery Investigation'}
        self.epg['FR - VOYAGE FHD'] = {'channel_id': 'Voyage'}
        self.epg['FR - USHUAIA TV FHD'] = {'channel_id': 'Ushuaia TV'}
        self.epg['FR - HISTOIRE FHD'] = {'channel_id': 'Histoire'}
        self.epg['FR - SCIENCES & VIE FHD'] = {'channel_id': 'Sciences & vie TV'}
        self.epg['FR - ANIMAUX FHD'] = {'channel_id': 'Animaux'}
        self.epg['FR - TREK FHD'] = {'channel_id': 'Trek'}
        self.epg['FR - SEASON FHD'] = {'channel_id': 'Seasons'}
        self.epg['FR - RMC DECOUVERTE FHD'] = {'channel_id': 'RMC Découverte'}
        self.epg['FR - BFM TV FHD'] = {'channel_id': 'BFM TV'}
        self.epg['FR - I24 NEWS FHD'] = {'channel_id': 'France 24'}
        self.epg['FR - LCI FHD'] = {'channel_id': 'LCI'}
        self.epg['FR - FRANCE INFO FHD'] = {'channel_id': 'Franceinfo'}
        self.epg['FR - BFM BUSINESS FHD'] = {'channel_id': 'BFM Business'}
        self.epg['FR - CANAL NEWS FHD'] = {'channel_id': 'CNews'}
        self.epg['FR - SFR SPORT1 FHD'] = {'channel_id': 'SFR Sport 1'}
        self.epg['FR - SFR SPORT2 FHD'] = {'channel_id': 'SFR Sport 2'}
        self.epg['FR - SFR SPORT3 FHD'] = {'channel_id': 'SFR Sport 3'}
        self.epg['FR - SFR SPORT5 FHD'] = {'channel_id': 'SFR Sport 5'}
        self.epg['FR - MOTORSPORT TV FHD'] = {'channel_id': 'Motors TV'}
        self.epg['FR - BEINSPORT1 FHD'] = {'channel_id': 'BeIN Sports 1'}
        self.epg['FR - BEINSPORT2 FHD'] = {'channel_id': 'BeIN Sports 2'}
        self.epg['FR - BEINSPORT3 FHD'] = {'channel_id': 'BeIN Sports 3'}
        self.epg['FR - INFOSPORT FHD'] = {'channel_id': 'Infosport+'}
        self.epg['FR - EUROSPORT1 FHD'] = {'channel_id': 'Eurosport'}
        self.epg['FR - EUROSPORT2 FHD'] = {'channel_id': 'Eurosport 2'}
        self.epg['FR - EXTREME SPORTS FHD'] = {'channel_id': 'Extreme Sports Channel'}
        self.epg['FR - L\'EQUIPE21 FHD'] = {'channel_id': 'L Equipe'}
        self.epg['FR - EQUIDIA LIFE FHD'] = {'channel_id': 'Equidia Life'}
        self.epg['FR - EQUIDIA LIVE FHD'] = {'channel_id': 'Equidia Live'}
        self.epg['FR - GOLF  FHD'] = {'channel_id': 'Golf +'}
        self.epg['FR - GOLF CHANNEL FHD'] = {'channel_id': 'Golf Channel'}
        self.epg['FR - BOOMERANG FHD'] = {'channel_id': 'Boomerang'}
        self.epg['FR - DISNEY JUNIOR FHD'] = {'channel_id': 'Disney Junior'}
        self.epg['FR - NICKELODEON FHD'] = {'channel_id': 'Nickelodéon'}
        self.epg['FR - CARTOON NETWORK FHD'] = {'channel_id': 'Cartoon Network'}
        self.epg['FR - DISNEY CHANNEL FHD'] = {'channel_id': 'Disney Channel'}
        self.epg['FR - DISNEY XD FHD'] = {'channel_id': 'Disney XD'}
        self.epg['FR - CANAL J FHD'] = {'channel_id': 'Canal J'}
        self.epg['FR - TIJI FHD'] = {'channel_id': 'Tiji'}
        self.epg['FR - BOING FHD'] = {'channel_id': 'Boing'}
        self.epg['FR - PIWI FHD'] = {'channel_id': 'Piwi+'}
        self.epg['FR - TELETOON  FHD'] = {'channel_id': 'TéléToon+'}
        self.epg['FR - MEZZO FHD'] = {'channel_id': 'Mezzo'}
        self.epg['FR - MEZZO LIVE FHD'] = {'channel_id': 'Mezzo Live HD'}
        self.epg['FR - AB3 FHD'] = {'channel_id': 'AB3'}
        self.epg['FR - CANAL8 FHD'] = {'channel_id': 'C8'}
        self.epg['FR - GULLI FHD'] = {'channel_id': 'Gulli'}
        self.epg['FR - MCM TOP FHD'] = {'channel_id': 'MCM Top'}
        self.epg['FR - MTV FRANCE FHD'] = {'channel_id': 'MTV'}
        self.epg['FR - MCM FHD'] = {'channel_id': 'MCM'}
        self.epg['FR - M6 MUSIC'] = {'channel_id': 'M6 Music'}
        self.epg['FR - ONE TV FHD'] = {'channel_id': 'One TV'}
        self.epg['FR - PARAMOUNT CHANNEL FHD'] = {'channel_id': 'Paramount Channel'}
        self.epg['FR - RFM TV FHD'] = {'channel_id': 'RFM TV'}
        self.epg['FR - TRACE URBAN FHD'] = {'channel_id': 'Trace Urban'}
        self.epg['FR - ELLE GIRL FHD'] = {'channel_id': 'Elle Girl'}
        self.epg['FR - TEVA HD'] = {'channel_id': 'Téva'}
        self.epg['FR - PARIS PREMIERE HD'] = {'channel_id': 'Paris Première'}
        self.epg['FR - TV 5 MONDE HD'] = {'channel_id': 'TV5 MONDE'}
        self.epg['FR - HD1 HD'] = {'channel_id': 'HD1'}
        self.epg['FR - NRJ 12 HD'] = {'channel_id': 'NRJ12'}
        self.epg['FR - LCP HD'] = {'channel_id': 'LCP / Public Sénat'}
        self.epg['FR - SERIE CLUB HD'] = {'channel_id': 'Serieclub'}
        self.epg['FR - KTO HD'] = {'channel_id': 'KTO'}
        self.epg['FR - EURONEWS HD'] = {'channel_id': 'Euronews'}
        self.epg['FR - AB MOTEUR HD'] = {'channel_id': 'AB Moteurs'}
        self.epg['FR - RMC SPORT NEWS'] = {'channel_id': 'RMC Sport News'}
        self.epg['FR - RMC SPORT 1 HD'] = {'channel_id': 'RMC Sport 1'}
        self.epg['FR - RMC SPORT 2 HD'] = {'channel_id': 'RMC Sport 2'}
        self.epg['FR - RMC SPORT 3 HD'] = {'channel_id': 'RMC Sport 3'}
        self.epg['FR - RMC SPORT 4 HD'] = {'channel_id': 'RMC Sport 4'}
        self.epg['FR - RMC ACCESS SPORT 1 HD'] = {'channel_id': 'RMC Access Sport 1'}
        self.epg['FR - RMC ACCESS SPORT 2 HD'] = {'channel_id': 'RMC Access Sport 2'}
        self.epg['FR - RMC ACCESS SPORT 3 HD'] = {'channel_id': 'RMC Access Sport 3'}
        self.epg['FR - RMC ACCESS SPORT 4 HD'] = {'channel_id': 'RMC Access Sport 4'}
        self.epg['FR - BEIN SPORT MAX 4 HD'] = {'channel_id': 'BEIN SPORTS MAX 4'}
        self.epg['FR - BEIN SPORT MAX 5 HD .'] = {'channel_id': 'BEIN SPORTS MAX 5'}
        self.epg['FR - BEIN SPORT MAX 6 HD'] = {'channel_id': 'BEIN SPORTS MAX 6'}
        self.epg['FR - BEIN SPORT MAX 7 HD'] = {'channel_id': 'BEIN SPORTS MAX 7'}
        self.epg['FR - BEIN SPORT MAX 8 HD'] = {'channel_id': 'BEIN SPORTS MAX 8'}
        self.epg['FR - BEIN SPORT MAX 9 HD'] = {'channel_id': 'BEIN SPORTS MAX 9'}

    def find(self, channel):
        return self.epg[channel]

    def channels(self):
        return self.epg.keys()
